streamers:
  - burzum_tv
  - kolmaniks
  - kochevnik
  - grpzdc
  - punisher3d
  - borzakua
  - alexsoft10
  - reihatori
  - lisiikot
  - ceh9
  - zhmil
  - artifixofficial
  - main_skeet
  - jesusavgn
  - olyashaa
  - revizzzor0
  - spb17o3
  - vatnik_russak
  - avemeliodas
  - uebermarginal
