streamers:
  - burzum_tv
  - kolmaniks
  - kochevnik
  - grpzdc
  - punisher3d
  - borzakua
  - reihatori
  - lisiikot
  - ceh9
  - spb17o3
  - vatnik_russak
  - avemeliodas
  - uebermarginal
  - d3l_by
 
