CREATE USER twirc WITH password 'twirc' NOSUPERUSER NOCREATEROLE NOCREATEDB;
CREATE DATABASE "twirc" OWNER twirc CONNECTION LIMIT 100;
\connect "twirc";
CREATE SCHEMA twirc AUTHORIZATION twirc;
ALTER DATABASE twirc SET DEFAULT_TRANSACTION_ISOLATION TO "READ COMMITTED";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
ALTER EXTENSION "uuid-ossp" SET SCHEMA twirc;
